name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [created]        
permissions:
  contents: write
jobs:
  Release-solution-ALMLab:
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      #You can specify the solution name here
      solution_name: AlmLab
      #Update your values here
      BUILD_ENVIRONMENT_URL: https://org061c07c9.crm4.dynamics.com/
      PRODUCTION_ENVIRONMENT_URL: https://org4e853047.crm4.dynamics.com/
      CLIENT_ID: 7a308651-fe2b-4917-9719-b2e42be33f7c
      TENANT_ID: 1a8f01a0-f16e-4fdb-b3c4-989b189d21ae      
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
